import os

BASE_DIR = os.path.dirname(os.path.abspath(__file__))
KHEAPS_DIR = os.path.join(BASE_DIR, "KHeaps")
CVE_DIR = os.path.join(KHEAPS_DIR, "exploit_env", "CVEs")
GRADER_DIR = os.path.join(KHEAPS_DIR, "grader")

DATA_DIR = os.path.join(BASE_DIR, "data")
RAW_DIR = os.path.join(DATA_DIR, "raw")
PROCESSED_DIR = os.path.join(DATA_DIR, "processed")

NORMAL_RAW_DIR = os.path.join(RAW_DIR, "normal")
ATTACK_RAW_DIR = os.path.join(RAW_DIR, "attack")
NORMAL_PROC_DIR = os.path.join(PROCESSED_DIR, "normal")
ATTACK_PROC_DIR = os.path.join(PROCESSED_DIR, "attack")

# Versioned v2 directories (IMPLEMENTATION_PLAN.md section 3). New code defaults
# to writing here; legacy data/ and results/ are left untouched.
DATASETS_DIR = os.path.join(BASE_DIR, "datasets")
LEGACY_V1_DIR = os.path.join(DATASETS_DIR, "legacy-v1")
PILOT_V2_DIR = os.path.join(DATASETS_DIR, "pilot-v2")
FINAL_V2_DIR = os.path.join(DATASETS_DIR, "final-v2")
RUNS_DIR = os.path.join(BASE_DIR, "runs")

CVE_LIST = [
    "CVE-2017-11176",
    "CVE-2017-7308",
    "CVE-2017-2636",
]

POC_VARIANTS = [
    "poc_cfh_baseline",
    "poc_cfh_single_spray",
    "poc_cfh_combo",
]

WORKLOADS = ["idle", "net_busy", "msg_msg"]

NORMAL_RUNS = 10
ATTACK_RUNS = 10
COLLECTION_DURATION = 30

TRACE_BUFFER_SIZE_KB = 16384
QEMU_CORES = 2
QEMU_MEM = 1

WINDOW_SIZE_MS = 100
WINDOW_STRIDE_MS = 50
SEQ_LEN = 32

# Dataset v2 uses the allocator's actual allocation size (bytes_alloc) and keeps
# an explicit overflow bucket. The old list collapsed every allocation larger
# than 2048 bytes into kmalloc-2048 even though several covered exploits target
# kmalloc-4096 objects.
SIZE_BUCKETS = [32, 64, 96, 128, 192, 256, 512, 1024, 2048, 4096, 8192]
SIZE_BUCKET_LABELS = [str(size) for size in SIZE_BUCKETS] + ["gt_8192"]
N_SIZE_BUCKETS = len(SIZE_BUCKET_LABELS)

# Feature layout is generated by scripts/preprocess/csv2features.py. It has six
# groups per size bucket plus 18 global/task/timing features.
FEAT_DIM = 6 * N_SIZE_BUCKETS + 18
DATASET_SCHEMA_VERSION = 2

LSTM_HIDDEN = 64
LSTM_LAYERS = 2
LATENT_DIM = 16
BETA_ANNEAL_EPOCHS = 20
EPOCHS = 100
LR = 1e-3
WEIGHT_DECAY = 1e-5
BATCH_SIZE = 128
FREE_BITS = 0.1

SSH_USER = "root"
SSH_HOST = "127.0.0.1"
REMOTE_TRACE_PATH = "/tmp/trace.log"
REMOTE_EXP_PATH = "/tmp/exp"
REMOTE_WORKLOAD_DIR = "/tmp/workloads"
